apiVersion: v1
kind: Service
metadata:
  name: "hydatis-{{.Release.Name }}"
  labels:
    app: "hydatis-{{.Release.Name }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.containerPort}}
      protocol: TCP
      name: http
  selector:
    app: "hydatis-{{.Release.Name }}"
